# Site settings
title: "WORS Wiki"
description: "Your one-stop knowledge base for WORS"
baseurl: "/WORS" # The subpath of your site, e.g. /WORS
url: "https://dagsvik.github.io" # Your GitHub Pages URL

# Theme settings
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
permalink: pretty

# Exclude files and directories from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Plugins (optional)
plugins:
  - jekyll-seo-tag # Adds SEO tags to your site
  - jekyll-sitemap # Generates a sitemap for your site

# Other settings
# Enable GitHub Flavored Markdown (GFM)
kramdown:
  input: GFM

# Enabling comments via Disqus (optional, only if you want comments)
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics (optional, only if you want to track site usage)
# google_analytics: UA-XXXXXXXX-X

